AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ComputeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: backend/
      Environment:
        Variables:
          TABLE_NAME: YourDynamoDBTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /compute
            Method: post
  ComputeTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: YourDynamoDBTable
      AttributeDefinitions:
        - AttributeName: a
          AttributeType: N
      KeySchema:
        - AttributeName: a
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
Outputs:
  ApiGatewayUrl:
    Description: "URL for API Gateway"
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/compute"
    Export:
      Name: "ApiGatewayUrl"
